### ISSUE TITLE
FOV like in Rogulike games

### ISSUE THREAD

**Issue by ghost** [darkfrei/love2d-lua-tests#1]
Please?

**Comment by darkfrei** [comment]
Hi!
What type of field-of-view are you mean?

**Comment by ghost** [comment]
https://i.redd.it/q2oxt7e8p3gy.png
https://tomassedovic.github.io/roguelike-tutorial/part-4-fov-exploration.html
Something like this

**Comment by darkfrei** [comment]
See this one: https://github.com/darkfrei/love2d-lua-tests/tree/main/field-of-view

**Comment by ghost** [comment]
Aww, thank you!
It really helped me!

**Comment by darkfrei** [comment]
New version is available!
